<?php if (Mage_Catalog_Block_Product_View_Type_Simple::displayProductStockStatus()): ?>
    <?php if (Mage::registry('current_product')->isAvailable()): ?>
        <p class="availability in-stock">
            <span class="label"><?php echo $this->helper('catalog')->__('Availability:') ?></span>
            <span class="value"><?php echo $this->helper('catalog')->__('In Stock') ?></span>
        </p>

    <?php else: ?>
        <p class="availability out-of-stock">
            <span class="label"><?php echo $this->helper('catalog')->__('Availability:') ?></span>
            <span class="value"><?php echo $this->helper('catalog')->__('0') ?></span>
        </p>
        <?php if(!Mage::getSingleton('customer/session')->isLoggedIn()): ?>
            <div class=".msg_message"></div>

            <label for="subs">Inform me when this product will be in Stock</label>
            <form id="subs" method="post" action="<?php echo Mage::getBaseUrl();?>productavailability/product/subscribe">
            <p>
                <input class="input-text required-entry" required type="email" name="email" placeholder="Enter your e-mail">
            </p>
                <input type="hidden" name="prodid" value="<?php echo $this->getProduct()->getId();?>">
            </form>
            <br>
            <button class="button senddd"><?php echo $this->helper('catalog')->__('Subscribe') ?></button>

            <?php else: ?>
            <div class=".msg_message"></div>
            <label for="subs">Inform me when this product will be in Stock</label>
            <form id="subs" method="post" action="<?php echo Mage::getBaseUrl();?>productavailability/product/subscribe">
                <input type="hidden" name="email"  value="<?php echo Mage::getSingleton('customer/session')->getCustomer()->getEmail();?>">
                <input type="hidden" name="prodid" value="<?php echo $this->getProduct()->getId();?>">
                <input type="hidden" name="userid" value="<?php echo Mage::getSingleton('customer/session')->getCustomer()->getId();?>">
                <input type="hidden" name="link" value="<?php echo $this->helper('core/url')->getCurrentUrl();?>">
                <br>
            </form>
            <br>
            <button class="button senddd"><?php echo $this->helper('catalog')->__('Subscribe') ?></button>
        <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>

